import { AppWrapper } from "@/components/AppWrapper";
import "./style.css";

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
      <html lang="en">
        <body>
          <nav><a href="/">Sentence Alignment Visualizer</a></nav>
          <div className="main">
            <AppWrapper>{children}</AppWrapper>
          </div>
        </body>
      </html>
  )
}
